---
- name: Install Apache2
  hosts: apache
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

- name: Install Nginx
  hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present


    
